/**
 * CANTENEX — Menu Data & Campus Configurations
 * Realistic Indian Canteen Specialties with authentic photography, nutrition macros & descriptions
 */

export const MENU_CATEGORIES = [
  { id: 'ALL', label: 'All Items', count: 36 },
  { id: 'BREAKFAST', label: 'Morning Tiffin', count: 7 },
  { id: 'MEALS', label: 'Lunch & Bowls', count: 9 },
  { id: 'SNACKS', label: 'Quick Bites', count: 8 },
  { id: 'DRINKS', label: 'Brews & Coolers', count: 8 },
  { id: 'DESSERTS', label: 'Sweet Finishes', count: 4 },
];

export const PICKUP_SLOTS = [
  { id: 'slot-1', label: '⚡ Ready in 10-12 Mins', type: 'immediate', desc: 'Current Kitchen Prep Queue' },
  { id: 'slot-2', label: '11:15 AM — Morning Break', type: 'scheduled', desc: 'Class Short Break (15 mins)' },
  { id: 'slot-3', label: '01:15 PM — Lunch Break', type: 'scheduled', desc: 'Main Campus Lunch Hour' },
  { id: 'slot-4', label: '03:45 PM — Evening Snack', type: 'scheduled', desc: 'Post-Lecture Tea Break' },
  { id: 'slot-5', label: '05:30 PM — After Hours', type: 'scheduled', desc: 'Evening Study & Lab Slot' },
];

export const DEPARTMENTS = [
  'Computer Science & Engineering',
  'Information Technology',
  'Electronics & Communication',
  'Mechanical Engineering',
  'Civil Engineering',
  'Electrical & Electronics',
  'Artificial Intelligence & DS',
  'Biotechnology',
  'Business Administration (MBA)',
];

export const INITIAL_MENU_ITEMS = [
  // -------------------------------------------------------------
  // BREAKFAST / MORNING TIFFIN (7 Items)
  // -------------------------------------------------------------
  {
    id: 'cx-01',
    code: '01',
    name: 'Ghee Podi Masala Dosa',
    category: 'BREAKFAST',
    price: 65,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Campus Bestseller',
    description: 'Crisp golden fermented rice crepe roasted in pure A2 ghee, generously dusted with gun-powder podi spice, filled with spiced potato masala, served with 3 house chutneys and hot sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '340 kcal',
    protein: '9g',
    carbs: '48g',
    fats: '12g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.9,
    highlight: true,
  },
  {
    id: 'cx-02',
    code: '02',
    name: 'Steamed Ghee Idli & Medu Vada Combo',
    category: 'BREAKFAST',
    price: 50,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Morning Ritual',
    description: 'Two cloud-soft button idlis dipped in clarified ghee paired with a crispy, freshly fried golden medu vada, served with traditional shallot drumstick sambar and fresh coconut dip.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '280 kcal',
    protein: '8g',
    carbs: '42g',
    fats: '8g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.8,
  },
  {
    id: 'cx-03',
    code: '03',
    name: 'Ven Pongal with Cashew Ghee Roast',
    category: 'BREAKFAST',
    price: 55,
    prepTime: '6 mins',
    diet: 'veg',
    tag: 'Comfort Bowl',
    description: 'Silky melt-in-mouth rice and yellow moong dal cooked with whole crushed black peppercorns, fresh ginger, curry leaves, and crunchy roasted cashews tempered in pure country butter.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    calories: '310 kcal',
    protein: '7g',
    carbs: '45g',
    fats: '11g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.7,
  },
  {
    id: 'cx-17',
    code: '17',
    name: 'Mysore Masala Dosa with Red Garlic Chutney',
    category: 'BREAKFAST',
    price: 70,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Fiery Crisp',
    description: 'Golden butter roasted crepe smeared with pungent red chili garlic Mysore paste, filled with spiced mashed potato filling, served with coconut chutney and piping hot drumstick sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '360 kcal',
    protein: '9g',
    carbs: '50g',
    fats: '14g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-18',
    code: '18',
    name: 'Puri Bhaji with Spiced Potato Masala (3 Pcs)',
    category: 'BREAKFAST',
    price: 55,
    prepTime: '6 mins',
    diet: 'veg',
    tag: 'Student Classic',
    description: 'Trio of puffed golden whole-wheat puris served with aromatic turmeric tempered cumin-potato bhaji, freshly sliced onions, green chilies, and tangy mango pickle.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    calories: '380 kcal',
    protein: '8g',
    carbs: '52g',
    fats: '16g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-19',
    code: '19',
    name: 'Crispy Onion Rava Dosa with Ginger Dip',
    category: 'BREAKFAST',
    price: 65,
    prepTime: '9 mins',
    diet: 'veg',
    tag: 'Golden Net',
    description: 'Delicate semolina lacy net crepe studded with crunchy chopped shallots, green chilies, crushed black peppercorns, and roasted cumin. Served crisp with allam ginger pachadi.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '320 kcal',
    protein: '7g',
    carbs: '46g',
    fats: '12g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.7,
  },
  {
    id: 'cx-20',
    code: '20',
    name: 'Lacy Kerala Appam with Vegetable Stew (2 Pcs)',
    category: 'BREAKFAST',
    price: 60,
    prepTime: '7 mins',
    diet: 'veg',
    tag: 'Coastal Delight',
    description: 'Fermented rice and coconut milk hopper with a soft spongy center and crispy lacy edges, paired with mildly spiced coconut milk stew laden with carrots, beans, and potatoes.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    calories: '260 kcal',
    protein: '6g',
    carbs: '44g',
    fats: '7g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.8,
  },

  // -------------------------------------------------------------
  // MEALS / LUNCH & BOWLS (9 Items)
  // -------------------------------------------------------------
  {
    id: 'cx-04',
    code: '04',
    name: 'Malabar Chicken Dum Biryani',
    category: 'MEALS',
    price: 130,
    prepTime: '7 mins',
    diet: 'non-veg',
    tag: "Chef's Signature",
    description: 'Fragrant short-grain Kaima rice layered with tender spiced chicken marinated in roasted Kerala spices, slow-cooked in dum style. Accompanied by mint onion raita, spicy pickle, and boiled farm egg.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=1200&q=85',
    calories: '580 kcal',
    protein: '32g',
    carbs: '65g',
    fats: '22g',
    inStock: true,
    spiceLevel: 3,
    rating: 5.0,
    featuredSpecial: true,
  },
  {
    id: 'cx-05',
    code: '05',
    name: 'Traditional South Indian Executive Meals',
    category: 'MEALS',
    price: 90,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Full Lunch Feast',
    description: 'Unlimited Ponni steamed rice served on eco-leaf with traditional Sambar, spicy Rasam, Kootu, Poriyal of the day, Appalam, curd, spicy pickle, and sweet Payasam.',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    calories: '520 kcal',
    protein: '14g',
    carbs: '78g',
    fats: '16g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-06',
    code: '06',
    name: 'Wok-Tossed Schezwan Egg & Chicken Fried Rice',
    category: 'MEALS',
    price: 95,
    prepTime: '10 mins',
    diet: 'non-veg',
    tag: 'Canteen Favorite',
    description: 'High-flame wok tossed basmati rice with shredded chicken, scrambled farm egg, crisp scallions, bell peppers, and fiery in-house Schezwan red pepper reduction.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=85',
    calories: '490 kcal',
    protein: '26g',
    carbs: '62g',
    fats: '15g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-07',
    code: '07',
    name: 'Flaky Kerala Parotta with Chicken Salna (2 Pcs)',
    category: 'MEALS',
    price: 80,
    prepTime: '6 mins',
    diet: 'non-veg',
    tag: 'Street Legend',
    description: 'Hand-beaten, multi-layered golden flaky Malabar parottas served steaming hot with rich, aromatic street-style chicken salna gravy and sliced red onions.',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '460 kcal',
    protein: '24g',
    carbs: '48g',
    fats: '20g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-21',
    code: '21',
    name: 'Hyderabadi Shahi Paneer Biryani Handi',
    category: 'MEALS',
    price: 115,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Royal Feast',
    description: 'Long-grain aged basmati rice cooked on slow dum with tandoor grilled cottage cheese cubes, caramelized fried onions (birista), saffron milk, mint leaves, and rich cucumber raita.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=1200&q=85',
    calories: '510 kcal',
    protein: '18g',
    carbs: '68g',
    fats: '19g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
    highlight: true,
  },
  {
    id: 'cx-22',
    code: '22',
    name: 'Paneer Butter Masala with 2 Butter Naan',
    category: 'MEALS',
    price: 110,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'North Indian Star',
    description: 'Silky paneer cubes simmered in a luscious velvet tomato cashew gravy enriched with butter and dried fenugreek kasuri methi, served with 2 freshly charred butter garlic naans.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '540 kcal',
    protein: '19g',
    carbs: '58g',
    fats: '26g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.9,
  },
  {
    id: 'cx-23',
    code: '23',
    name: 'Student Mini Thali (Dal Makhani & Jeera Rice)',
    category: 'MEALS',
    price: 85,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Everyday Saver',
    description: 'Slow-simmered black lentils in creamy butter gravy, fragrant cumin basmati rice, 2 hot phulkas, fresh pickled onions, and roasted papad for a wholesome lecture break lunch.',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    calories: '450 kcal',
    protein: '15g',
    carbs: '65g',
    fats: '14g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.7,
  },
  {
    id: 'cx-24',
    code: '24',
    name: 'Street-Style Chicken Hakka Noodles',
    category: 'MEALS',
    price: 95,
    prepTime: '9 mins',
    diet: 'non-veg',
    tag: 'Wok Master',
    description: 'Springy egg noodles tossed in high-heat wok with tender chicken strips, crisp cabbage, julienned carrots, scallions, dark soy sauce, and crushed white peppercorns.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    calories: '470 kcal',
    protein: '25g',
    carbs: '59g',
    fats: '16g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-25',
    code: '25',
    name: 'Comfort Curd Rice with Tadka & Pomegranate',
    category: 'MEALS',
    price: 45,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Cooling Bowl',
    description: 'Creamy homemade curd mixed with soft mashed rice, tempered with mustard seeds, curry leaves, ginger, green chilies, roasted urad dal, and sweet ruby pomegranate pearls.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '260 kcal',
    protein: '7g',
    carbs: '42g',
    fats: '7g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.8,
  },

  // -------------------------------------------------------------
  // SNACKS / QUICK BITES (8 Items)
  // -------------------------------------------------------------
  {
    id: 'cx-08',
    code: '08',
    name: 'Charcoal Grilled Paneer Tikka Kathi Roll',
    category: 'SNACKS',
    price: 75,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Grab & Go',
    description: 'Succulent malai paneer cubes marinated in tandoori spices, rolled in a flaky butter parotta with pickled laccha onions, mint coriander chutney, and chatpata chaat masala.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    calories: '390 kcal',
    protein: '16g',
    carbs: '44g',
    fats: '17g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.7,
  },
  {
    id: 'cx-09',
    code: '09',
    name: 'Delhi Style Samosa Chaat Platter (2 Pcs)',
    category: 'SNACKS',
    price: 45,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Evening Craving',
    description: 'Crisp pastry triangles stuffed with spiced potatoes and green peas, crushed and drowned in hot ragda chole, whisked yogurt, sweet tamarind glaze, spicy mint chutney, and nylon sev.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '320 kcal',
    protein: '8g',
    carbs: '46g',
    fats: '12g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-10',
    code: '10',
    name: 'Peri Peri Seasoned Crispy Golden Fries',
    category: 'SNACKS',
    price: 60,
    prepTime: '7 mins',
    diet: 'veg',
    tag: 'Addictive Crunch',
    description: 'Double-fried hand-cut Idaho potato batons tossed immediately in spicy African bird’s eye peri-peri seasoning. Served with creamy garlic dip.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    calories: '350 kcal',
    protein: '5g',
    carbs: '48g',
    fats: '16g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.6,
  },
  {
    id: 'cx-26',
    code: '26',
    name: 'Kolkata Double Egg & Chicken Roll',
    category: 'SNACKS',
    price: 85,
    prepTime: '8 mins',
    diet: 'non-veg',
    tag: 'Protein Loaded',
    description: 'Layered flaky parotta lined with two farm eggs, stuffed with spicy roasted shredded chicken, crunchy sliced red onions, green chilies, fresh lime juice, and Kasundi mustard mayo.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=1200&q=85',
    calories: '440 kcal',
    protein: '28g',
    carbs: '42g',
    fats: '18g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-27',
    code: '27',
    name: 'Crispy Onion & Palak Pakoda Basket',
    category: 'SNACKS',
    price: 40,
    prepTime: '6 mins',
    diet: 'veg',
    tag: 'Rainy Day Crunch',
    description: 'Golden, extra-crisp fritters made from thinly sliced red onions and tender baby spinach coated in ajwain-spiced gram flour batter. Served with spicy pudina mint chutney.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    calories: '290 kcal',
    protein: '6g',
    carbs: '36g',
    fats: '14g',
    inStock: true,
    spiceLevel: 2,
    rating: 4.7,
  },
  {
    id: 'cx-28',
    code: '28',
    name: 'Mumbai Butter Pav Bhaji (2 Butter Pavs)',
    category: 'SNACKS',
    price: 70,
    prepTime: '7 mins',
    diet: 'veg',
    tag: 'Campus Sensation',
    description: 'Spicy mashed vegetable curry enriched with pure Amul butter, special Pav Bhaji masala, served with 2 golden pan-toasted butter pavs, fresh lemon wedges, and chopped red onions.',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    calories: '420 kcal',
    protein: '10g',
    carbs: '56g',
    fats: '18g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
    highlight: true,
  },
  {
    id: 'cx-29',
    code: '29',
    name: 'Crispy Vegetable Spring Rolls with Sweet Chili (4 Pcs)',
    category: 'SNACKS',
    price: 55,
    prepTime: '6 mins',
    diet: 'veg',
    tag: 'Golden Crispy',
    description: 'Crispy golden pastry rolls packed with wok-tossed shredded cabbage, bell peppers, carrots, and sweet corn. Served hot with homemade sweet garlic chili dip.',
    image: 'https://images.unsplash.com/photo-1548507297-c20ec26b52c0?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    calories: '280 kcal',
    protein: '6g',
    carbs: '38g',
    fats: '12g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.7,
  },
  {
    id: 'cx-30',
    code: '30',
    name: 'Crunchy Southern Spiced Chicken Popcorn',
    category: 'SNACKS',
    price: 80,
    prepTime: '6 mins',
    diet: 'non-veg',
    tag: 'Crunch Blast',
    description: 'Bite-sized boneless chicken morsels marinated in buttermilk and south-Indian curry leaf masala, breaded and fried to supreme crunch. Served with smoked garlic dip.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    calories: '370 kcal',
    protein: '24g',
    carbs: '28g',
    fats: '18g',
    inStock: true,
    spiceLevel: 3,
    rating: 4.8,
  },

  // -------------------------------------------------------------
  // DRINKS / BREWS & COOLERS (8 Items)
  // -------------------------------------------------------------
  {
    id: 'cx-11',
    code: '11',
    name: 'Brass Tumbler Degree Filter Coffee',
    category: 'DRINKS',
    price: 25,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Soul Brew',
    description: 'Freshly decocted 80:20 Peaberry Chicory brew frothed with full-cream hot milk, poured from height to create a velvety foam crown. Served in traditional brass dabarah.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85',
    calories: '110 kcal',
    protein: '4g',
    carbs: '14g',
    fats: '4g',
    inStock: true,
    spiceLevel: 0,
    rating: 5.0,
  },
  {
    id: 'cx-12',
    code: '12',
    name: 'Kolkata Kulhad Masala Chai',
    category: 'DRINKS',
    price: 20,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Rainy Day Special',
    description: 'Assam CTC tea leaves slow-simmered with crushed green cardamom, dried ginger, cloves, and cinnamon bark, served in an earthy terracotta kulhad.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '90 kcal',
    protein: '3g',
    carbs: '12g',
    fats: '3g',
    inStock: true,
    spiceLevel: 1,
    rating: 4.9,
  },
  {
    id: 'cx-13',
    code: '13',
    name: 'Belgian Dark Chocolate Frappé Cold Coffee',
    category: 'DRINKS',
    price: 65,
    prepTime: '4 mins',
    diet: 'veg',
    tag: 'Chilled Fuel',
    description: 'Double espresso shot blended with rich Belgian chocolate ganache, chilled dairy, and crushed ice, topped with cocoa dusting and espresso foam.',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '220 kcal',
    protein: '6g',
    carbs: '28g',
    fats: '9g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-14',
    code: '14',
    name: 'Shikanji Fresh Mint Lime Crusher',
    category: 'DRINKS',
    price: 35,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Hydration Burst',
    description: 'Hand-squeezed Kagzi lime juice shaken with crushed garden spearmint, roasted cumin rock salt, cane sugar, and sparkling soda or chilled water.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=85',
    calories: '75 kcal',
    protein: '1g',
    carbs: '18g',
    fats: '0g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.7,
  },
  {
    id: 'cx-31',
    code: '31',
    name: 'Chilled Royal Rose Milk with Sabja Seeds',
    category: 'DRINKS',
    price: 40,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Summer Classic',
    description: 'Thick farm fresh chilled milk blended with aromatic rose petal syrup, floating soaked basil (sabja) seeds, and crushed ice for instant campus refreshment.',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=85',
    calories: '160 kcal',
    protein: '5g',
    carbs: '24g',
    fats: '5g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.8,
  },
  {
    id: 'cx-32',
    code: '32',
    name: 'Alphonso Mango Lassi with Roasted Pistachios',
    category: 'DRINKS',
    price: 55,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Creamy Mango',
    description: 'Velvety sweet yogurt churned with real Ratnagiri Alphonso mango pulp, a hint of cardamom, topped with chopped Iranian pistachios and saffron threads.',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=85',
    calories: '210 kcal',
    protein: '7g',
    carbs: '32g',
    fats: '6g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-33',
    code: '33',
    name: 'Iced Lemon Peach Hibiscus Brew',
    category: 'DRINKS',
    price: 40,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Zero Guilt Cooler',
    description: 'Cold-brewed organic crimson hibiscus flowers infused with white peach essence, squeezed lemon juice, and a splash of wild mountain honey over cracked ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '60 kcal',
    protein: '0g',
    carbs: '14g',
    fats: '0g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.7,
  },
  {
    id: 'cx-34',
    code: '34',
    name: 'Warm Kesariya Badam Milk with Crushed Cashews',
    category: 'DRINKS',
    price: 45,
    prepTime: '4 mins',
    diet: 'veg',
    tag: 'Nutritious Warmth',
    description: 'Rich boiling milk infused with ground almond paste, Kashmiri saffron strands, cardamom powder, and garnished with roasted golden cashew bits.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '190 kcal',
    protein: '8g',
    carbs: '22g',
    fats: '8g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },

  // -------------------------------------------------------------
  // DESSERTS / SWEET FINISHES (4 Items)
  // -------------------------------------------------------------
  {
    id: 'cx-15',
    code: '15',
    name: 'Sizzling Warm Belgian Walnut Brownie',
    category: 'DESSERTS',
    price: 80,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Decadent Melt',
    description: 'Dense, fudgy 70% dark chocolate brownie packed with roasted California walnuts, warmed through and served with rich chocolate hot fudge drizzle.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    calories: '410 kcal',
    protein: '6g',
    carbs: '46g',
    fats: '22g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-16',
    code: '16',
    name: 'Royal Shahi Malai Kulfi on Bamboo Stick',
    category: 'DESSERTS',
    price: 50,
    prepTime: '2 mins',
    diet: 'veg',
    tag: 'Traditional Chilled',
    description: 'Slow-reduced whole buffalo milk infused with Kashmiri saffron strands, green cardamom, chopped Iranian pistachios, and slivered almonds.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=85',
    calories: '240 kcal',
    protein: '5g',
    carbs: '26g',
    fats: '13g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.8,
  },
  {
    id: 'cx-35',
    code: '35',
    name: 'Hot Desi Ghee Gulab Jamun with Rabdi (2 Pcs)',
    category: 'DESSERTS',
    price: 55,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Pure Indulgence',
    description: 'Soft golden fried mawa dumplings soaked in rose cardamom sugar syrup, served warm alongside a generous ladle of chilled slow-simmered rabdi.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    calories: '310 kcal',
    protein: '6g',
    carbs: '42g',
    fats: '14g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-36',
    code: '36',
    name: 'Rich Saffron Gajar Ka Halwa with Mawa & Nuts',
    category: 'DESSERTS',
    price: 65,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Winter Specialty',
    description: 'Slow-cooked grated Delhi carrots in pure country ghee and full-cream milk, sweetened with raw sugar, studded with roasted cashews, raisins, and crumbled mawa.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=85',
    calories: '290 kcal',
    protein: '5g',
    carbs: '38g',
    fats: '13g',
    inStock: true,
    spiceLevel: 0,
    rating: 4.8,
  },
];

export const INITIAL_ORDERS = [
  {
    id: 'CX-1021',
    studentName: 'Dinesh C',
    regNo: '22BCS142',
    department: 'Computer Science & Engineering',
    items: [
      { id: 'cx-04', name: 'Malabar Chicken Dum Biryani', price: 130, quantity: 1 },
      { id: 'cx-14', name: 'Shikanji Fresh Mint Lime Crusher', price: 35, quantity: 1 },
    ],
    totalAmount: 165,
    pickupSlot: '01:15 PM — Lunch Break',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'READY',
    counter: 'Counter 2 (Hot Express)',
    placedAt: '12:48 PM',
    prepProgress: 90,
  },
  {
    id: 'cx-1022',
    studentName: 'Sneha Rangarajan',
    regNo: '23BIT089',
    department: 'Information Technology',
    items: [
      { id: 'cx-01', name: 'Ghee Podi Masala Dosa', price: 65, quantity: 2 },
      { id: 'cx-11', name: 'Brass Tumbler Degree Filter Coffee', price: 25, quantity: 2 },
    ],
    totalAmount: 180,
    pickupSlot: '⚡ Ready in 10-12 Mins',
    pickupType: 'immediate',
    paymentMethod: 'Cash at Counter',
    status: 'PREPARING',
    counter: 'Counter 1 (Tiffin & Dosa)',
    placedAt: '01:02 PM',
    prepProgress: 55,
  },
  {
    id: 'cx-1023',
    studentName: 'Rohan Deshmukh',
    regNo: '21BME205',
    department: 'Mechanical Engineering',
    items: [
      { id: 'cx-07', name: 'Flaky Kerala Parotta with Salna', price: 80, quantity: 1 },
      { id: 'cx-13', name: 'Belgian Dark Chocolate Cold Coffee', price: 65, quantity: 1 },
    ],
    totalAmount: 145,
    pickupSlot: '01:15 PM — Lunch Break',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'ACCEPTED',
    counter: 'Counter 3 (Special Gravy)',
    placedAt: '01:08 PM',
    prepProgress: 25,
  },
  {
    id: 'cx-1024',
    studentName: 'Kavya Sree',
    regNo: '24BAI017',
    department: 'Artificial Intelligence & DS',
    items: [
      { id: 'cx-08', name: 'Paneer Tikka Kathi Roll', price: 75, quantity: 1 },
      { id: 'cx-15', name: 'Sizzling Warm Brownie', price: 80, quantity: 1 },
    ],
    totalAmount: 155,
    pickupSlot: '03:45 PM — Evening Snack',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'PLACED',
    counter: 'Counter 2 (Hot Express)',
    placedAt: '01:12 PM',
    prepProgress: 10,
  },
  {
    id: 'cx-1025',
    studentName: 'Aditya Verma',
    regNo: '22ECE114',
    department: 'Electronics & Communication',
    items: [
      { id: 'cx-28', name: 'Mumbai Butter Pav Bhaji', price: 70, quantity: 1 },
      { id: 'cx-32', name: 'Alphonso Mango Lassi', price: 55, quantity: 1 },
    ],
    totalAmount: 125,
    pickupSlot: '⚡ Ready in 10-12 Mins',
    pickupType: 'immediate',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'ACCEPTED',
    counter: 'Counter 2 (Hot Express)',
    placedAt: '01:18 PM',
    prepProgress: 35,
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    menuId: 'cx-04',
    studentName: 'Dinesh C. (CSE)',
    rating: 5,
    comment: 'The chicken dum biryani is incredible! Dum aroma is authentic and chicken pieces are super tender.',
    date: 'Today, 12:45 PM'
  },
  {
    id: 'rev-2',
    menuId: 'cx-01',
    studentName: 'Sneha R. (IT)',
    rating: 5,
    comment: 'Podi dosa is crisp to perfection. Love the fiery gunpowder spice and ginger chutney.',
    date: 'Today, 10:30 AM'
  },
  {
    id: 'rev-3',
    menuId: 'cx-11',
    studentName: 'Rohan D. (Mech)',
    rating: 5,
    comment: 'Authentic degree filter coffee. Perfect frothy head in the brass dabarah!',
    date: 'Today, 09:15 AM'
  },
  {
    id: 'rev-4',
    menuId: 'cx-15',
    studentName: 'Kavya S. (AI&DS)',
    rating: 5,
    comment: 'Warm walnut brownie with hot chocolate sauce is a lifesaver between continuous lectures.',
    date: 'Yesterday, 04:20 PM'
  },
  {
    id: 'rev-5',
    menuId: 'cx-28',
    studentName: 'Aditya V. (ECE)',
    rating: 5,
    comment: 'Pav Bhaji with extra butter is phenomenal! Genuine Mumbai street style flavor on campus.',
    date: 'Today, 01:25 PM'
  },
  {
    id: 'rev-6',
    menuId: 'cx-17',
    studentName: 'Pooja K. (Biotech)',
    rating: 5,
    comment: 'The red garlic chutney spread inside Mysore masala dosa gives it the ultimate punch!',
    date: 'Today, 11:40 AM'
  },
];
