/**
 * CANTENEX — Menu Data & Campus Configurations
 * Realistic Indian Canteen Specialties with authentic photography & descriptions
 */

export const MENU_CATEGORIES = [
  { id: 'ALL', label: 'All Items', count: 16 },
  { id: 'BREAKFAST', label: 'Morning Tiffin', count: 3 },
  { id: 'MEALS', label: 'Lunch & Bowls', count: 4 },
  { id: 'SNACKS', label: 'Quick Bites', count: 3 },
  { id: 'DRINKS', label: 'Brews & Coolers', count: 4 },
  { id: 'DESSERTS', label: 'Sweet Finishes', count: 2 },
];

export const PICKUP_SLOTS = [
  { id: 'slot-1', label: '⚡ Ready in 10-12 Mins', type: 'immediate', desc: 'Current Kitchen Prep Queue' },
  { id: 'slot-2', label: '11:15 AM — Morning Break', type: 'scheduled', desc: 'Class Short Break (15 mins)' },
  { id: 'slot-3', label: '01:15 PM — Lunch Break', type: 'scheduled', desc: 'Main Campus Lunch Hour' },
  { id: 'slot-4', label: '03:45 PM — Evening Snack', type: 'scheduled', desc: 'Post-Lecture Tea Break' },
  { id: 'slot-5', label: '05:30 PM — After Hours', type: 'scheduled', desc: 'Evening Study & Lab Slot' },
];

export const DEPARTMENTS = [
  'Computer Science & Engineering',
  'Information Technology',
  'Electronics & Communication',
  'Mechanical Engineering',
  'Civil Engineering',
  'Electrical & Electronics',
  'Artificial Intelligence & DS',
  'Biotechnology',
  'Business Administration (MBA)',
];

export const INITIAL_MENU_ITEMS = [
  {
    id: 'cx-01',
    code: '01',
    name: 'Ghee Podi Masala Dosa',
    category: 'BREAKFAST',
    price: 65,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Campus Bestseller',
    description: 'Crisp golden fermented rice crepe roasted in pure A2 ghee, generously dusted with gun-powder podi spice, filled with spiced potato masala, served with 3 house chutneys and hot sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '340 kcal',
    inStock: true,
    spiceLevel: 2,
    rating: 4.9,
    highlight: true,
  },
  {
    id: 'cx-02',
    code: '02',
    name: 'Steamed Ghee Idli & Medu Vada Combo',
    category: 'BREAKFAST',
    price: 50,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Morning Ritual',
    description: 'Two cloud-soft button idlis dipped in clarified ghee paired with a crispy, freshly fried golden medu vada, served with traditional shallot drumstick sambar and fresh coconut dip.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '280 kcal',
    inStock: true,
    spiceLevel: 1,
    rating: 4.8,
  },
  {
    id: 'cx-03',
    code: '03',
    name: 'Ven Pongal with Cashew Ghee Roast',
    category: 'BREAKFAST',
    price: 55,
    prepTime: '6 mins',
    diet: 'veg',
    tag: 'Comfort Bowl',
    description: 'Silky melt-in-mouth rice and yellow moong dal cooked with whole crushed black peppercorns, fresh ginger, curry leaves, and crunchy roasted cashews tempered in pure country butter.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    calories: '310 kcal',
    inStock: true,
    spiceLevel: 1,
    rating: 4.7,
  },
  {
    id: 'cx-04',
    code: '04',
    name: 'Malabar Chicken Dum Biryani',
    category: 'MEALS',
    price: 130,
    prepTime: '7 mins',
    diet: 'non-veg',
    tag: "Chef's Signature",
    description: 'Fragrant short-grain Kaima rice layered with tender spiced chicken marinated in roasted Kerala spices, slow-cooked in dum style. Accompanied by mint onion raita, spicy pickle, and boiled farm egg.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=1200&q=85',
    calories: '580 kcal',
    inStock: true,
    spiceLevel: 3,
    rating: 5.0,
    featuredSpecial: true,
  },
  {
    id: 'cx-05',
    code: '05',
    name: 'Traditional South Indian Executive Meals',
    category: 'MEALS',
    price: 90,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Full Lunch Feast',
    description: 'Unlimited Ponni steamed rice served on eco-leaf with traditional Sambar, spicy Rasam, Kootu, Poriyal of the day, Appalam, curd, spicy pickle, and sweet Payasam.',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=85',
    calories: '520 kcal',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-06',
    code: '06',
    name: 'Wok-Tossed Schezwan Egg & Chicken Fried Rice',
    category: 'MEALS',
    price: 95,
    prepTime: '10 mins',
    diet: 'non-veg',
    tag: 'Canteen Favorite',
    description: 'High-flame wok tossed basmati rice with shredded chicken, scrambled farm egg, crisp scallions, bell peppers, and fiery in-house Schezwan red pepper reduction.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=85',
    calories: '490 kcal',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-07',
    code: '07',
    name: 'Flaky Kerala Parotta with Chicken Salna (2 Pcs)',
    category: 'MEALS',
    price: 80,
    prepTime: '6 mins',
    diet: 'non-veg',
    tag: 'Street Legend',
    description: 'Hand-beaten, multi-layered golden flaky Malabar parottas served steaming hot with rich, aromatic street-style chicken salna gravy and sliced red onions.',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    calories: '460 kcal',
    inStock: true,
    spiceLevel: 3,
    rating: 4.9,
  },
  {
    id: 'cx-08',
    code: '08',
    name: 'Charcoal Grilled Paneer Tikka Kathi Roll',
    category: 'SNACKS',
    price: 75,
    prepTime: '8 mins',
    diet: 'veg',
    tag: 'Grab & Go',
    description: 'Succulent malai paneer cubes marinated in tandoori spices, rolled in a flaky butter parotta with pickled laccha onions, mint coriander chutney, and chatpata chaat masala.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    calories: '390 kcal',
    inStock: true,
    spiceLevel: 2,
    rating: 4.7,
  },
  {
    id: 'cx-09',
    code: '09',
    name: 'Delhi Style Samosa Chaat Platter (2 Pcs)',
    category: 'SNACKS',
    price: 45,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Evening Craving',
    description: 'Crisp pastry triangles stuffed with spiced potatoes and green peas, crushed and drowned in hot ragda chole, whisked yogurt, sweet tamarind glaze, spicy mint chutney, and nylon sev.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=85',
    calories: '320 kcal',
    inStock: true,
    spiceLevel: 2,
    rating: 4.8,
  },
  {
    id: 'cx-10',
    code: '10',
    name: 'Peri Peri Seasoned Crispy Golden Fries',
    category: 'SNACKS',
    price: 60,
    prepTime: '7 mins',
    diet: 'veg',
    tag: 'Addictive Crunch',
    description: 'Double-fried hand-cut Idaho potato batons tossed immediately in spicy African bird’s eye peri-peri seasoning. Served with creamy garlic dip.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
    calories: '350 kcal',
    inStock: true,
    spiceLevel: 2,
    rating: 4.6,
  },
  {
    id: 'cx-11',
    code: '11',
    name: 'Brass Tumbler Degree Filter Coffee',
    category: 'DRINKS',
    price: 25,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Soul Brew',
    description: 'Freshly decocted 80:20 Peaberry Chicory brew frothed with full-cream hot milk, poured from height to create a velvety foam crown. Served in traditional brass dabarah.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85',
    calories: '110 kcal',
    inStock: true,
    spiceLevel: 0,
    rating: 5.0,
  },
  {
    id: 'cx-12',
    code: '12',
    name: 'Kolkata Kulhad Masala Chai',
    category: 'DRINKS',
    price: 20,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Rainy Day Special',
    description: 'Assam CTC tea leaves slow-simmered with crushed green cardamom, dried ginger, cloves, and cinnamon bark, served in an earthy terracotta kulhad.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '90 kcal',
    inStock: true,
    spiceLevel: 1,
    rating: 4.9,
  },
  {
    id: 'cx-13',
    code: '13',
    name: 'Belgian Dark Chocolate Frappé Cold Coffee',
    category: 'DRINKS',
    price: 65,
    prepTime: '4 mins',
    diet: 'veg',
    tag: 'Chilled Fuel',
    description: 'Double espresso shot blended with rich Belgian chocolate ganache, chilled dairy, and crushed ice, topped with cocoa dusting and espresso foam.',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=85',
    calories: '220 kcal',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-14',
    code: '14',
    name: 'Shikanji Fresh Mint Lime Crusher',
    category: 'DRINKS',
    price: 35,
    prepTime: '3 mins',
    diet: 'veg',
    tag: 'Hydration Burst',
    description: 'Hand-squeezed Kagzi lime juice shaken with crushed garden spearmint, roasted cumin rock salt, cane sugar, and sparkling soda or chilled water.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=1200&q=85',
    calories: '75 kcal',
    inStock: true,
    spiceLevel: 0,
    rating: 4.7,
  },
  {
    id: 'cx-15',
    code: '15',
    name: 'Sizzling Warm Belgian Walnut Brownie',
    category: 'DESSERTS',
    price: 80,
    prepTime: '5 mins',
    diet: 'veg',
    tag: 'Decadent Melt',
    description: 'Dense, fudgy 70% dark chocolate brownie packed with roasted California walnuts, warmed through and served with rich chocolate hot fudge drizzle.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    calories: '410 kcal',
    inStock: true,
    spiceLevel: 0,
    rating: 4.9,
  },
  {
    id: 'cx-16',
    code: '16',
    name: 'Royal Shahi Malai Kulfi on Bamboo Stick',
    category: 'DESSERTS',
    price: 50,
    prepTime: '2 mins',
    diet: 'veg',
    tag: 'Traditional Chilled',
    description: 'Slow-reduced whole buffalo milk infused with Kashmiri saffron strands, green cardamom, chopped Iranian pistachios, and slivered almonds.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=85',
    fallbackImage: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=85',
    calories: '240 kcal',
    inStock: true,
    spiceLevel: 0,
    rating: 4.8,
  },
];

export const INITIAL_ORDERS = [
  {
    id: 'CX-1021',
    studentName: 'Dinesh C',
    regNo: '22BCS142',
    department: 'Computer Science & Engineering',
    items: [
      { id: 'cx-04', name: 'Malabar Chicken Dum Biryani', price: 130, quantity: 1 },
      { id: 'cx-14', name: 'Shikanji Fresh Mint Lime Crusher', price: 35, quantity: 1 },
    ],
    totalAmount: 165,
    pickupSlot: '01:15 PM — Lunch Break',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'READY',
    counter: 'Counter 2 (Hot Express)',
    placedAt: '12:48 PM',
    prepProgress: 90,
  },
  {
    id: 'cx-1022',
    studentName: 'Sneha Rangarajan',
    regNo: '23BIT089',
    department: 'Information Technology',
    items: [
      { id: 'cx-01', name: 'Ghee Podi Masala Dosa', price: 65, quantity: 2 },
      { id: 'cx-11', name: 'Brass Tumbler Degree Filter Coffee', price: 25, quantity: 2 },
    ],
    totalAmount: 180,
    pickupSlot: '⚡ Ready in 10-12 Mins',
    pickupType: 'immediate',
    paymentMethod: 'Cash at Counter',
    status: 'PREPARING',
    counter: 'Counter 1 (Tiffin & Dosa)',
    placedAt: '01:02 PM',
    prepProgress: 55,
  },
  {
    id: 'cx-1023',
    studentName: 'Rohan Deshmukh',
    regNo: '21BME205',
    department: 'Mechanical Engineering',
    items: [
      { id: 'cx-07', name: 'Flaky Kerala Parotta with Salna', price: 80, quantity: 1 },
      { id: 'cx-13', name: 'Belgian Dark Chocolate Cold Coffee', price: 65, quantity: 1 },
    ],
    totalAmount: 145,
    pickupSlot: '01:15 PM — Lunch Break',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'ACCEPTED',
    counter: 'Counter 3 (Special Gravy)',
    placedAt: '01:08 PM',
    prepProgress: 25,
  },
  {
    id: 'cx-1024',
    studentName: 'Kavya Sree',
    regNo: '24BAI017',
    department: 'Artificial Intelligence & DS',
    items: [
      { id: 'cx-08', name: 'Paneer Tikka Kathi Roll', price: 75, quantity: 1 },
      { id: 'cx-15', name: 'Sizzling Warm Brownie', price: 80, quantity: 1 },
    ],
    totalAmount: 155,
    pickupSlot: '03:45 PM — Evening Snack',
    pickupType: 'scheduled',
    paymentMethod: 'UPI Demo (Verified)',
    status: 'PLACED',
    counter: 'Counter 2 (Hot Express)',
    placedAt: '01:12 PM',
    prepProgress: 10,
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    menuId: 'cx-04',
    studentName: 'Dinesh C. (CSE)',
    rating: 5,
    comment: 'The chicken dum biryani is incredible! Dum aroma is authentic and chicken pieces are super tender.',
    date: 'Today, 12:45 PM'
  },
  {
    id: 'rev-2',
    menuId: 'cx-01',
    studentName: 'Sneha R. (IT)',
    rating: 5,
    comment: 'Podi dosa is crisp to perfection. Love the fiery gunpowder spice and ginger chutney.',
    date: 'Today, 10:30 AM'
  },
  {
    id: 'rev-3',
    menuId: 'cx-11',
    studentName: 'Rohan D. (Mech)',
    rating: 5,
    comment: 'Authentic degree filter coffee. Perfect frothy head in the brass dabarah!',
    date: 'Today, 09:15 AM'
  },
  {
    id: 'rev-4',
    menuId: 'cx-15',
    studentName: 'Kavya S. (AI&DS)',
    rating: 5,
    comment: 'Warm walnut brownie with hot chocolate sauce is a lifesaver between continuous lectures.',
    date: 'Yesterday, 04:20 PM'
  }
];

